apiVersion: v2
name: jupyter-tensorflow-gpu
description: The JupyterLab IDE with Python and the deep-learning framework TensorFlow,
  with GPU support.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/jupyter.png
keywords:
- Jupyter
- Python
home: https://jupyter.org/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 2.2.7
dependencies:
- name: library-chart
  version: 1.6.8
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
