apiVersion: v2
name: jupyter-python-gpu
description: The JupyterLab IDE with Python, Julia, and a collection of standard data
  science packages, with GPU support.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/jupyter.png
keywords:
- Jupyter
- Python
home: https://jupyter.org/
sources:
- https://github.com/InseeFrLab/helm-charts-interactive-services/tree/main/charts/jupyter-python-gpu
- https://github.com/InseeFrLab/images-datascience
type: application
version: 1.13.33
dependencies:
- name: library-chart
  version: 1.5.21
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
