apiVersion: v2
name: jupyter-python-gpu
description: The JupyterLab IDE with Python, and a collection of standard data science
  packages, with GPU support.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/jupyter.png
keywords:
- Jupyter
- Python
home: https://jupyter.org/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 2.3.5
dependencies:
- name: library-chart
  version: 1.7.1
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
