apiVersion: v2
name: vscode-r
description: The VSCode IDE with R and a collection of standard data science packages.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
keywords:
- VSCode
- Python
home: https://code.visualstudio.com/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 2.1.2
dependencies:
- name: library-chart
  version: 1.5.25
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
