apiVersion: v2
name: rstudio-sparkr
description: The RStudio IDE with a collection of standard data science packages. It includes SparkR, an R package that provides an interface to use Apache Spark from R.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/rstudio.png
keywords:
  - RStudio
  - R
  - Spark
home: https://www.rstudio.com/
sources:
  - https://github.com/InseeFrLab/images-datascience
  - https://github.com/InseeFrLab/helm-charts-interactive-services
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.4.1

dependencies:
  - name: library-chart
    version: 1.2.1
    repository: https://inseefrlab.github.io/helm-charts-interactive-services
