apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eostat-autoshutdown.serviceAccountName" . }}
  labels:
    {{- include "eostat-autoshutdown.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eostat-autoshutdown.fullname" . }}
  labels:
    {{- include "eostat-autoshutdown.labels" . | nindent 4 }}
rules:
  # Read pods to check age
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # Read and update Helm release secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
  # Update StatefulSets for helm to reconcile
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eostat-autoshutdown.fullname" . }}
  labels:
    {{- include "eostat-autoshutdown.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eostat-autoshutdown.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eostat-autoshutdown.serviceAccountName" . }}
