apiVersion: v2
name: vscode-pytorch
description: The VSCode IDE with Python and the deep-learning framework PyTorch.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
keywords:
- VSCode
- Python
home: https://code.visualstudio.com/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 2.1.21
dependencies:
- name: library-chart
  version: 1.5.39
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
