apiVersion: v2
name: eostat-rstudio
description: RStudio environment for Earth Observation Statistics with R and geospatial libraries
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/rstudio.png
keywords:
- RStudio
- Earth Observation
- Remote Sensing
- Geospatial
- R
home: https://fao-eostat.github.io/UN-Handbook/
sources:
- https://github.com/UNGlobalPlatform/images-datascience
- https://github.com/UNGlobalPlatform/helm-charts-interactive-services
maintainers:
- name: UN Global Platform
  email: lovells@un.org
type: application
version: 0.2.2
dependencies:
- name: library-chart
  version: 1.7.14
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
