apiVersion: v2
name: vscode-pytorch-gpu
description: The VSCode IDE with Python and the deep-learning framework PyTorch, with
  GPU support.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
keywords:
- VSCode
- Python
home: https://code.visualstudio.com/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 2.4.5
dependencies:
- name: library-chart
  version: 2.0.3
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
