apiVersion: v2
name: vscode-tensorflow
description: The VSCode IDE with Python and the deep-learning framework TensorFlow.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
keywords:
- VSCode
- Python
home: https://code.visualstudio.com/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 2.3.12
dependencies:
- name: library-chart
  version: 1.7.5
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
