apiVersion: v2
name: vscode-python-gpu
description: The VSCOde IDE with Python, Julia, and a collection of standard data
  science packages, with GPU support.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
keywords:
- VSCode
- Python
home: https://code.visualstudio.com/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 1.8.2
dependencies:
- name: library-chart
  version: 1.3.11
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
