apiVersion: v2
name: vscode-python-gpu
description: The VSCOde IDE with Python, Julia, and a collection of standard data
  science packages, with GPU support.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
keywords:
- VSCode
- Python
- Julia
home: https://code.visualstudio.com/
sources:
- https://github.com/InseeFrLab/images-datascience/tree/main/vscode
- https://github.com/InseeFrLab/images-datascience/tree/main/python
- https://github.com/InseeFrLab/helm-charts-datascience-internal/tree/main/charts/vscode
type: application
version: 1.1.1
appVersion: 4.7.1
dependencies:
- name: library-chart
  version: 1.0.3
  repository: https://inseefrlab.github.io/helm-charts-datascience-internal
