apiVersion: v2
name: jupyter-tensorflow
description: The JupyterLab IDE with Python and the deep-learning framework TensorFlow.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/jupyter.png
keywords:
- Jupyter
- Python
home: https://jupyter.org/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 1.13.6
dependencies:
- name: library-chart
  version: 1.5.12
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
